### PR TITLE
[98] add query for curator comments

### PR DESCRIPTION
**Pull request by stanislaw-zakrzewski**
Solves: #98 

Changes:
* Free-text search now is capable of searching through the curator comments
* Highlighter now works with combinations of terms (quoted)
* DataGuideDialog component content was updated 

#### Screenshots:
Searching for a case with free-text (content in curators comment):
image
image

Updated DataGuideDialog content:
image

### CODE REVIEW

**Review by shaileshmahajanBCH — CHANGES_REQUESTED** [review]
Hello @stanislaw-zakrzewski , 
- The data guide and single word search **looks good**.
image

image


-  I do see following **issue with search** for terms like `hello $`, `hello /`, `hello, this`. Can you please take a look if there are some restrictions on search terms

image

**Comment by stanislaw-zakrzewski** [comment]
Hey @shaileshmahajanBCH 
There were some issues regarding the filers and text search combinations. Hopefully I managed to resolve them as well as searching for special characterd.

**Review by shaileshmahajanBCH — CHANGES_REQUESTED** [review]
Thanks @stanislaw-zakrzewski for all the work on this PR.

- Did notice that the search is not returning case records some times. I have 2 cases with the word "this" in it, But search result does not return that case

image

image

**Review by shaileshmahajanBCH — APPROVED** [review]
@stanislaw-zakrzewski You are correct. Stop words are not indexed. 

- This link says the same - https://www.mongodb.com/docs/manual/core/indexes/index-types/index-text/specify-text-index-language/

- **May be quickly run it by Aimee or Product person** to get their blessings, As they may need to know/document the stop words.

**Pull request merged**
